---
- hosts: all
  vars:
    http_port: 80
    max_clients: 200
  remote_user: root

  tasks:
    - name: Setting HTTPS if nginx.yml error
      template: 
        src: template/nginx.j2
        dest: /etc/nginx/sites-available/default

    - name: Restart nginx
      service:
        service: name=nginx state=restarted enabled=yes
